name: Build and run Rust tests
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - rust/**
      - protos/**
      - .github/workflows/rust.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  # This env var is used by Swatinem/rust-cache@v2 for the cache
  # key, so we set it to make sure it is always consistent.
  CARGO_TERM_COLOR: always
  # Disable full debug symbol generation to speed up CI build and keep memory down
  # "1" means line tables only, which is useful for panic tracebacks.
  RUSTFLAGS: "-C debuginfo=1"
  RUST_BACKTRACE: "1"
  # according to: https://matklad.github.io/2021/09/04/fast-rust-builds.html
  # CI builds are faster with incremental disabled.
  CARGO_INCREMENTAL: "0"
  CARGO_BUILD_JOBS: "1"

jobs:
  mac-build-11:
    runs-on: "macos-11"
    timeout-minutes: 45
    strategy:
      matrix:
        toolchain:
          - stable
    defaults:
      run:
        working-directory: ./rust/lance
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: rust
      - name: Install dependencies
        run: brew install protobuf
      - name: Run tests
        run: |
          cargo build --target aarch64-apple-darwin --all-features
  mac-build-12:
    runs-on: "macos-12"
    timeout-minutes: 45
    strategy:
      matrix:
        toolchain:
          - stable
    defaults:
      run:
        working-directory: ./rust/lance
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: rust
      - name: Install dependencies
        run: brew install protobuf
      - name: Run tests
        run: |
          cargo build --target aarch64-apple-darwin --all-features
  mac-build-13:
    runs-on: "macos-13"
    timeout-minutes: 45
    strategy:
      matrix:
        toolchain:
          - stable
    defaults:
      run:
        working-directory: ./rust/lance
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: rust
      - name: Install dependencies
        run: brew install protobuf
      - name: Run tests
        run: |
          cargo build --target aarch64-apple-darwin --all-features
  mac-build-14:
    runs-on: "macos-14"
    timeout-minutes: 45
    strategy:
      matrix:
        toolchain:
          - stable
    defaults:
      run:
        working-directory: ./rust/lance
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: rust
      - name: Install dependencies
        run: brew install protobuf
      - name: Run tests
        run: |
          cargo build --target aarch64-apple-darwin --all-features